### ISSUE TITLE
Robots

### ISSUE THREAD

**Issue by mlaga97** [eaglemakerhub/reading-learning-toys#1]
Two robots need to be designed and produced, one red and one blue. Real batteries will be used so robot size should be approximate to that. Robots can have a hollow belly, but batteries do not need to be able to snap inside.

**Comment by iMoto251** [comment]
Print at 1000% scale to get best result for 4 AAA batteries to fit.
[Robot.zip](https://github.com/eaglemakerhub/reading-learning-toys/files/3677602/Robot.zip)

**Comment by iMoto251** [comment]
Print at 1000% if face breaks off robot
[Head.zip](https://github.com/eaglemakerhub/reading-learning-toys/files/3697852/Head.zip)
